---
# Play 1: локально — токен и сертификат
- name: Panel API (local)
  hosts: localhost
  gather_facts: false
  roles:
    - role: panel_api

# Play 2: на узлах — апдейт, Docker, контейнер, прокси
- name: Provision node
  hosts: marzban_nodes
  become: true
  roles:
    - { role: os_update, tags: [update, upgrade] }
    - marzban_node
    - haproxy
    - nginx

# Play 3: регистрация (делегируется на localhost)
- name: Register nodes in panel
  hosts: marzban_nodes
  gather_facts: false
  tasks:
    - name: "Role: panel_register"
      ansible.builtin.import_role:
        name: panel_register
      tags: [panel_register]
      when: (panel_register_enabled | default(true)) | bool
