---
# Play 1: локально — токен и сертификат
- name: Panel API (local)
  hosts: localhost
  gather_facts: false
  roles:
    - role: panel_api

# Play 2: на узлах — апдейт, TLS, контейнер, прокси
- name: Provision node
  hosts: marzban_nodes
  become: true
  roles:
    # апдейты ОС можно запускать выборочно тегами update,upgrade
    - { role: os_update, tags: [update, upgrade] }

    # Синхронизация wildcard-сертификата с cert-master на узел
    - { role: tls_sync, tags: [tls_sync] }

    # Контейнер узла (при необходимости — берет cert панели из Play 1)
    - role: marzban_node
      tags: [marzban_node]
      # пробросим сертификат панели в роль (если panel_api его получал)
      panel_certificate: "{{ hostvars['localhost'].panel_certificate | default('') }}"

    # Прокси-слой
    - { role: haproxy, tags: [haproxy] }
    - { role: nginx, tags: [nginx] }

# Play 3: регистрация (делегируется на localhost)
- name: Register nodes in panel
  hosts: marzban_nodes
  gather_facts: false
  tasks:
    - name: "Role: panel_register"
      ansible.builtin.import_role:
        name: panel_register
      tags: [panel_register]
      when: (panel_register_enabled | default(true)) | bool
