---
- name: Add node to panel (delegated)
  ansible.builtin.uri:
    url: "{{ panel_register_url }}/api/node"
    method: POST
    headers:
      Authorization: "Bearer {{ panel_register_access_token }}"
    body_format: json
    body:
      name: "{{ (panel_register_node_name | default('')) or inventory_hostname }}"
      address: >-
        {{
          (panel_register_address | default('')) or
          (hostvars[inventory_hostname].ansible_host | default(inventory_hostname))
        }}
      port: "{{ panel_register_service_port }}"
      api_port: "{{ panel_register_api_port }}"
      add_as_new_host: "{{ panel_register_add_as_new_host | bool }}"
      usage_coefficient: "{{ panel_register_usage_coefficient | float }}"
    return_content: true
    status_code: [200, 201]
    validate_certs: "{{ panel_register_validate_certs | bool }}"
  delegate_to: localhost
