# Значения по умолчанию; можно перекрывать -e или в inventory.
service_port: 62050
api_port: 62051
add_as_new_host: true
usage_coefficient: 1.0
service_protocol: "rest"     # включаем REST на узле (рекомендовано) :contentReference[oaicite:4]{index=4}

# Проверка TLS панели в Ansible uri-запросах:
panel_validate_certs: true

website_domains:
  - site.digitalstreamers.xyz
  - www.digitalstreamers.xyz

# nginx TLS (поменяйте на реальные сертификаты в проде)
nginx_ssl_cert: /etc/ssl/certs/ssl-cert-snakeoil.pem
nginx_ssl_key:  /etc/ssl/private/ssl-cert-snakeoil.key

# бинды сервисов
nginx_https_bind: 127.0.0.1:8443
xray_tcp_bind:    127.0.0.1:8444